# Generated by Django 4.2.30 on 2026-09-21 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0002_documentoinstitucional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloGestionProveedores',
            fields=[
                ('id', models.AutoField(db_column='id_mod_prov', primary_key=True, serialize=False)),
                ('fo_sistema', models.ForeignKey(db_column='fo_sistema', on_delete=django.db.models.deletion.CASCADE, to='administracion.sistematrainet')),
            ],
            options={
                'db_table': 'modulo_gestion_proveedores',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(db_column='id_proveedor', primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('calificacion', models.IntegerField(default=0)),
                ('rut', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=255)),
                ('fo_mod_prov', models.ForeignKey(db_column='fo_mod_prov', on_delete=django.db.models.deletion.CASCADE, to='proveedores.modulogestionproveedores')),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='ServicioProveedor',
            fields=[
                ('id', models.AutoField(db_column='id_servicio', primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=255)),
                ('fo_proveedor', models.ForeignKey(db_column='fo_proveedor', on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
            options={
                'db_table': 'servicio_proveedor',
            },
        ),
        migrations.CreateModel(
            name='NecesidadCapacitacionExterna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('fo_mod_prov', models.ForeignKey(db_column='fo_mod_prov', on_delete=django.db.models.deletion.CASCADE, to='proveedores.modulogestionproveedores')),
                ('fo_usuario', models.ForeignKey(db_column='fo_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'necesidad_capacitacion_externa',
            },
        ),
        migrations.CreateModel(
            name='CotizacionProveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='cotizaciones_proveedor/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fo_proveedor', models.ForeignKey(db_column='fo_proveedor', on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
            options={
                'db_table': 'cotizacion_proveedor',
            },
        ),
        migrations.CreateModel(
            name='ContratoProveedor',
            fields=[
                ('id', models.AutoField(db_column='id_contrato', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], max_length=50)),
                ('fo_proveedor', models.ForeignKey(db_column='fo_proveedor', on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
            options={
                'db_table': 'contrato_proveedor',
            },
        ),
    ]
