# Generated by Django 4.2.30 on 2026-09-21 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionProveedor',
            fields=[
                ('id', models.AutoField(db_column='id_evaluacion_calidad', primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField(default=0)),
                ('fecha_evaluacion', models.DateField()),
                ('fo_proveedor', models.ForeignKey(db_column='fo_proveedor', on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
            options={
                'db_table': 'evaluacion_proveedor',
            },
        ),
    ]
