# Generated by Django 4.2.30 on 2026-10-03 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def marcar_proveedores_contratados(apps, schema_editor):
    # Los proveedores que ya tienen un contrato vigente quedan como "contratado".
    Proveedor = apps.get_model('proveedores', 'Proveedor')
    ContratoProveedor = apps.get_model('proveedores', 'ContratoProveedor')
    ids = ContratoProveedor.objects.filter(estado='vigente').values_list('fo_proveedor_id', flat=True)
    Proveedor.objects.filter(id__in=list(ids)).update(estado='contratado')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proveedores', '0002_evaluacionproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoproveedor',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='contratos_proveedor/'),
        ),
        migrations.AddField(
            model_name='contratoproveedor',
            name='confirmacion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contratoproveedor',
            name='fo_cotizacion',
            field=models.ForeignKey(blank=True, db_column='fo_cotizacion', null=True, on_delete=django.db.models.deletion.PROTECT, to='proveedores.cotizacionproveedor'),
        ),
        migrations.AddField(
            model_name='contratoproveedor',
            name='fo_usuario',
            field=models.ForeignKey(blank=True, db_column='fo_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacionproveedor',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='cotizacionproveedor',
            name='fo_usuario',
            field=models.ForeignKey(blank=True, db_column='fo_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(choices=[('sin_contratar', 'Sin contratar'), ('contratado', 'Contratado'), ('inactivo', 'Inactivo')], default='sin_contratar', max_length=30),
        ),
        migrations.AlterField(
            model_name='contratoproveedor',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='vigente', max_length=50),
        ),
        migrations.RunPython(marcar_proveedores_contratados, migrations.RunPython.noop),
    ]
