# Generated by Django 4.2.30 on 2026-10-03 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proveedores', '0003_gestion_proveedores_flujo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoproveedor',
            name='fecha_decision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratoproveedor',
            name='fo_aprobador',
            field=models.ForeignKey(blank=True, db_column='fo_aprobador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_decididos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratoproveedor',
            name='motivo_decision',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contratoproveedor',
            name='estado',
            field=models.CharField(choices=[('pendiente_aprobacion', 'Pendiente de aprobación'), ('vigente', 'Vigente'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('rechazado', 'Rechazado')], default='pendiente_aprobacion', max_length=50),
        ),
    ]
