# Generated by Django 4.2.30 on 2026-09-20 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0002_documentoinstitucional'),
        ('usuarios', '0002_tecnicosoporte_supervisor_recursoshumanos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloPedidoRecursos',
            fields=[
                ('id', models.AutoField(db_column='id_mod_pedido', primary_key=True, serialize=False)),
                ('presupuesto_asignado', models.IntegerField(default=0)),
                ('fo_sistema', models.ForeignKey(db_column='fo_sistema', on_delete=django.db.models.deletion.CASCADE, to='administracion.sistematrainet')),
            ],
            options={
                'db_table': 'modulo_pedido_recursos',
            },
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id', models.AutoField(db_column='id_tipo_recurso', primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=255)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_recurso',
            },
        ),
        migrations.CreateModel(
            name='SolicitudRecursos',
            fields=[
                ('id', models.AutoField(db_column='id_solicitud', primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('justificacion', models.CharField(max_length=255)),
                ('prioridad', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('presupuesto_estimado', models.IntegerField(default=0)),
                ('comentario_encargado', models.CharField(blank=True, max_length=255)),
                ('archivo_entrega', models.FileField(blank=True, null=True, upload_to='entregas_recursos/')),
                ('fo_empleado', models.ForeignKey(db_column='fo_empleado', on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado')),
                ('fo_mod_pedido', models.ForeignKey(db_column='fo_mod_pedido', on_delete=django.db.models.deletion.CASCADE, to='recursos.modulopedidorecursos')),
                ('fo_tipo_recurso', models.ForeignKey(db_column='fo_tipo_recurso', on_delete=django.db.models.deletion.CASCADE, to='recursos.tiporecurso')),
            ],
            options={
                'db_table': 'solicitud_recursos',
            },
        ),
    ]
