# Generated by Django 4.2.30 on 2026-09-20 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudrecursos',
            name='fo_empleado',
        ),
        migrations.AddField(
            model_name='solicitudrecursos',
            name='fo_usuario',
            field=models.ForeignKey(db_column='fo_usuario', default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudrecursos',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('entregado', 'Entregado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='solicitudrecursos',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=255),
        ),
    ]
