# Generated by Django 4.2.30 on 2026-09-20 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_tecnicosoporte_supervisor_recursoshumanos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaTrainet',
            fields=[
                ('id', models.AutoField(db_column='id_sistema', primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=255)),
                ('fecha_instalacion', models.DateField()),
            ],
            options={
                'db_table': 'sistema_trainet',
            },
        ),
        migrations.CreateModel(
            name='ProcesoCargo',
            fields=[
                ('id', models.AutoField(db_column='id_proceso', primary_key=True, serialize=False)),
                ('nombre_proceso', models.CharField(max_length=255)),
                ('fo_enc_admin', models.ForeignKey(db_column='fo_enc_admin', on_delete=django.db.models.deletion.CASCADE, to='usuarios.encargadoadministrativo')),
            ],
            options={
                'db_table': 'proceso_cargo',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(db_column='id_permiso', primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(max_length=255)),
                ('fo_administrador', models.ForeignKey(db_column='fo_administrador', on_delete=django.db.models.deletion.CASCADE, to='usuarios.administrador')),
            ],
            options={
                'db_table': 'permiso',
            },
        ),
        migrations.CreateModel(
            name='ModuloAdministracion',
            fields=[
                ('id', models.AutoField(db_column='id_mod_admin', primary_key=True, serialize=False)),
                ('fo_sistema', models.ForeignKey(db_column='fo_sistema', on_delete=django.db.models.deletion.CASCADE, to='administracion.sistematrainet')),
            ],
            options={
                'db_table': 'modulo_administracion',
            },
        ),
        migrations.CreateModel(
            name='ModuloActivo',
            fields=[
                ('id', models.AutoField(db_column='id_modulo_activo', primary_key=True, serialize=False)),
                ('nombre_modulo', models.CharField(max_length=255)),
                ('fo_sistema', models.ForeignKey(db_column='fo_sistema', on_delete=django.db.models.deletion.CASCADE, to='administracion.sistematrainet')),
            ],
            options={
                'db_table': 'modulo_activo',
            },
        ),
        migrations.CreateModel(
            name='ModuloAcceso',
            fields=[
                ('id', models.AutoField(db_column='id_modulo_acceso', primary_key=True, serialize=False)),
                ('nombre_modulo', models.CharField(max_length=255)),
                ('fo_administrador', models.ForeignKey(db_column='fo_administrador', on_delete=django.db.models.deletion.CASCADE, to='usuarios.administrador')),
            ],
            options={
                'db_table': 'modulo_acceso',
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.AutoField(db_column='id_log_auditoria', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_evento', models.DateField(auto_now_add=True)),
                ('fo_mod_admin', models.ForeignKey(db_column='fo_mod_admin', on_delete=django.db.models.deletion.CASCADE, to='administracion.moduloadministracion')),
                ('fo_usuario', models.ForeignKey(db_column='fo_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_auditoria',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.AutoField(db_column='id_configuracion_sistema', primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('fo_mod_admin', models.ForeignKey(db_column='fo_mod_admin', on_delete=django.db.models.deletion.CASCADE, to='administracion.moduloadministracion')),
            ],
            options={
                'db_table': 'configuracion_sistema',
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(db_column='id_configuracion', primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('fo_sistema', models.ForeignKey(db_column='fo_sistema', on_delete=django.db.models.deletion.CASCADE, to='administracion.sistematrainet')),
            ],
            options={
                'db_table': 'configuracion',
            },
        ),
        migrations.CreateModel(
            name='AreasResponsabilidad',
            fields=[
                ('id', models.AutoField(db_column='id_area', primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(max_length=255)),
                ('fo_directivo', models.ForeignKey(db_column='fo_directivo', on_delete=django.db.models.deletion.CASCADE, to='usuarios.directivo')),
            ],
            options={
                'db_table': 'areas_responsabilidad',
            },
        ),
    ]
