# Generated by Django 4.2.30 on 2026-09-20 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoInstitucional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('archivo', models.FileField(upload_to='documentos_institucionales/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fo_usuario', models.ForeignKey(db_column='fo_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documento_institucional',
            },
        ),
    ]
