# Generated by Django 4.2.30 on 2026-10-03 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administracion', '0002_documentoinstitucional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logauditoria',
            options={'ordering': ['-fecha_hora', '-id']},
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='accion',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='fecha_hora',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='modulo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='configuracionsistema',
            name='clave',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='fecha_evento',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='fo_usuario',
            field=models.ForeignKey(blank=True, db_column='fo_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
