# Generated by Django 4.2.30 on 2026-09-21 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0002_documentoinstitucional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaFrecuente',
            fields=[
                ('id', models.AutoField(db_column='id_consulta', primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=255)),
                ('respuesta', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='respuestas_asistente/')),
            ],
            options={
                'db_table': 'consulta_frecuente',
            },
        ),
        migrations.CreateModel(
            name='ModuloAsistenteVirtual',
            fields=[
                ('id', models.AutoField(db_column='id_mod_asistente', primary_key=True, serialize=False)),
                ('fo_sistema', models.ForeignKey(db_column='fo_sistema', on_delete=django.db.models.deletion.CASCADE, to='administracion.sistematrainet')),
            ],
            options={
                'db_table': 'modulo_asistente_virtual',
            },
        ),
        migrations.CreateModel(
            name='HistorialConsulta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta_usuario', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fo_consulta_frecuente', models.ForeignKey(blank=True, db_column='fo_consulta_frecuente', null=True, on_delete=django.db.models.deletion.CASCADE, to='asistente.consultafrecuente')),
                ('fo_usuario', models.ForeignKey(db_column='fo_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_consulta',
            },
        ),
        migrations.AddField(
            model_name='consultafrecuente',
            name='fo_mod_asistente',
            field=models.ForeignKey(db_column='fo_mod_asistente', on_delete=django.db.models.deletion.CASCADE, to='asistente.moduloasistentevirtual'),
        ),
        migrations.CreateModel(
            name='BaseConocimiento',
            fields=[
                ('id', models.AutoField(db_column='id_base', primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=255)),
                ('contenido', models.CharField(max_length=255)),
                ('fo_mod_asistente', models.ForeignKey(db_column='fo_mod_asistente', on_delete=django.db.models.deletion.CASCADE, to='asistente.moduloasistentevirtual')),
            ],
            options={
                'db_table': 'base_conocimiento',
            },
        ),
    ]
