# Generated by Django 4.2.30 on 2026-10-03 06:39

from django.db import migrations, models
import django.db.models.deletion


def marcar_resueltas(apps, schema_editor):
    """Las consultas históricas que ya tenían respuesta asociada quedan como resueltas."""
    HistorialConsulta = apps.get_model('asistente', 'HistorialConsulta')
    HistorialConsulta.objects.filter(fo_consulta_frecuente__isnull=False).update(resuelta=True)


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultafrecuente',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='consultafrecuente',
            name='palabras_clave',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='historialconsulta',
            name='origen',
            field=models.CharField(choices=[('texto', 'Texto'), ('menu', 'Menú')], default='texto', max_length=10),
        ),
        migrations.AddField(
            model_name='historialconsulta',
            name='resuelta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historialconsulta',
            name='util',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultafrecuente',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='asistente/'),
        ),
        migrations.AlterField(
            model_name='consultafrecuente',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='consultafrecuente',
            name='respuesta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historialconsulta',
            name='fo_consulta_frecuente',
            field=models.ForeignKey(blank=True, db_column='fo_consulta_frecuente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistente.consultafrecuente'),
        ),
        migrations.AlterField(
            model_name='historialconsulta',
            name='pregunta_usuario',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='CategoriaAsistente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('icono', models.CharField(default='bi-chat-dots', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fo_mod_asistente', models.ForeignKey(db_column='fo_mod_asistente', on_delete=django.db.models.deletion.CASCADE, to='asistente.moduloasistentevirtual')),
            ],
            options={
                'db_table': 'categoria_asistente',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='consultafrecuente',
            name='fo_categoria',
            field=models.ForeignKey(blank=True, db_column='fo_categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistente.categoriaasistente'),
        ),
        migrations.RunPython(marcar_resueltas, migrations.RunPython.noop),
    ]
