# Generated by Django 4.2.30 on 2026-09-20 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0002_documentoinstitucional'),
        ('usuarios', '0002_tecnicosoporte_supervisor_recursoshumanos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTicket',
            fields=[
                ('id', models.AutoField(db_column='id_cat_ticket', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categoria_ticket',
            },
        ),
        migrations.CreateModel(
            name='ModuloSoporteTecnico',
            fields=[
                ('id', models.AutoField(db_column='id_mod_soporte', primary_key=True, serialize=False)),
                ('tiempo_respuesta', models.IntegerField(default=0)),
                ('fo_sistema', models.ForeignKey(db_column='fo_sistema', on_delete=django.db.models.deletion.CASCADE, to='administracion.sistematrainet')),
            ],
            options={
                'db_table': 'modulo_soporte_tecnico',
            },
        ),
        migrations.CreateModel(
            name='TicketSoporte',
            fields=[
                ('id', models.AutoField(db_column='id_ticket', primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('prioridad', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('tiempo_resolucion', models.IntegerField(default=0)),
                ('fo_categoria_ticket', models.ForeignKey(db_column='fo_categoria_ticket', on_delete=django.db.models.deletion.CASCADE, to='soporte.categoriaticket')),
                ('fo_mod_soporte', models.ForeignKey(db_column='fo_mod_soporte', on_delete=django.db.models.deletion.CASCADE, to='soporte.modulosoportetecnico')),
                ('fo_tecnico', models.ForeignKey(db_column='fo_tecnico', on_delete=django.db.models.deletion.CASCADE, to='usuarios.tecnicosoporte')),
                ('fo_usuario', models.ForeignKey(db_column='fo_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket_soporte',
            },
        ),
        migrations.CreateModel(
            name='EvidenciaTicket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='evidencias_ticket/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fo_ticket', models.ForeignKey(db_column='fo_ticket', on_delete=django.db.models.deletion.CASCADE, to='soporte.ticketsoporte')),
            ],
            options={
                'db_table': 'evidencia_ticket',
            },
        ),
    ]
