# Generated by Django 4.2.30 on 2026-09-21 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_tecnicosoporte_supervisor_recursoshumanos_and_more'),
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudComun',
            fields=[
                ('id', models.AutoField(db_column='id_sol_comun', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fo_mod_soporte', models.ForeignKey(db_column='fo_mod_soporte', on_delete=django.db.models.deletion.CASCADE, to='soporte.modulosoportetecnico')),
            ],
            options={
                'db_table': 'solicitud_comun',
            },
        ),
        migrations.CreateModel(
            name='HerramientaTecnico',
            fields=[
                ('id', models.AutoField(db_column='id_herramienta_manejo', primary_key=True, serialize=False)),
                ('nombre_herramienta', models.CharField(max_length=255)),
                ('fo_tecnico', models.ForeignKey(db_column='fo_tecnico', on_delete=django.db.models.deletion.CASCADE, to='usuarios.tecnicosoporte')),
            ],
            options={
                'db_table': 'herramienta_tecnico',
            },
        ),
    ]
