# Generated by Django 4.2.30 on 2026-10-03 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_tecnicosoporte_supervisor_recursoshumanos_and_more'),
        ('soporte', '0002_solicitudcomun_herramientatecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsoporte',
            name='fecha_resolucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketsoporte',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ticketsoporte',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketsoporte',
            name='fo_tecnico',
            field=models.ForeignKey(blank=True, db_column='fo_tecnico', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.tecnicosoporte'),
        ),
        migrations.AlterField(
            model_name='ticketsoporte',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=255),
        ),
    ]
