# Generated by Django 4.2.30 on 2026-09-21 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0002_documentoinstitucional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloReportes',
            fields=[
                ('id', models.AutoField(db_column='id_mod_reportes', primary_key=True, serialize=False)),
                ('fo_sistema', models.ForeignKey(db_column='fo_sistema', on_delete=django.db.models.deletion.CASCADE, to='administracion.sistematrainet')),
            ],
            options={
                'db_table': 'modulo_reportes',
            },
        ),
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id', models.AutoField(db_column='id_tipo_reporte', primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=255)),
                ('fo_mod_reportes', models.ForeignKey(db_column='fo_mod_reportes', on_delete=django.db.models.deletion.CASCADE, to='reportes.moduloreportes')),
            ],
            options={
                'db_table': 'tipo_reporte',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(db_column='id_reporte', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('archivo_generado', models.FileField(blank=True, null=True, upload_to='reportes_generados/')),
                ('fo_mod_reportes', models.ForeignKey(db_column='fo_mod_reportes', on_delete=django.db.models.deletion.CASCADE, to='reportes.moduloreportes')),
                ('fo_tipo_reporte', models.ForeignKey(db_column='fo_tipo_reporte', on_delete=django.db.models.deletion.CASCADE, to='reportes.tiporeporte')),
                ('fo_usuario', models.ForeignKey(db_column='fo_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reporte',
            },
        ),
        migrations.CreateModel(
            name='ParametroReporte',
            fields=[
                ('id', models.AutoField(db_column='id_parametro', primary_key=True, serialize=False)),
                ('clave_parametro', models.CharField(max_length=255)),
                ('valor_parametro', models.CharField(max_length=255)),
                ('fo_reporte', models.ForeignKey(db_column='fo_reporte', on_delete=django.db.models.deletion.CASCADE, to='reportes.reporte')),
            ],
            options={
                'db_table': 'parametro_reporte',
            },
        ),
        migrations.CreateModel(
            name='FrecuenciaReporte',
            fields=[
                ('id', models.AutoField(db_column='id_frecuencia', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fo_mod_reportes', models.ForeignKey(db_column='fo_mod_reportes', on_delete=django.db.models.deletion.CASCADE, to='reportes.moduloreportes')),
            ],
            options={
                'db_table': 'frecuencia_reporte',
            },
        ),
        migrations.CreateModel(
            name='DatoReporte',
            fields=[
                ('id', models.AutoField(db_column='id_dato', primary_key=True, serialize=False)),
                ('descripcion_dato', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='datos_reporte/')),
                ('fo_reporte', models.ForeignKey(db_column='fo_reporte', on_delete=django.db.models.deletion.CASCADE, to='reportes.reporte')),
            ],
            options={
                'db_table': 'dato_reporte',
            },
        ),
    ]
