# Generated by Django 4.2.30 on 2026-10-03 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporeporte',
            name='origen',
            field=models.CharField(choices=[('archivo', 'Archivo importado'), ('sistema', 'Datos del sistema')], default='sistema', max_length=10),
        ),
        migrations.CreateModel(
            name='ArchivoImportado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('archivo', models.FileField(upload_to='reportes/importados/')),
                ('formato', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX')], max_length=4)),
                ('fecha_documento', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('filas', models.PositiveIntegerField(default=0)),
                ('columnas', models.PositiveIntegerField(default=0)),
                ('encabezados', models.TextField(blank=True, default='[]')),
                ('huella', models.CharField(max_length=64, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fo_mod_reportes', models.ForeignKey(db_column='fo_mod_reportes', on_delete=django.db.models.deletion.CASCADE, to='reportes.moduloreportes')),
                ('fo_tipo', models.ForeignKey(db_column='fo_tipo', on_delete=django.db.models.deletion.PROTECT, to='reportes.tiporeporte')),
                ('fo_usuario', models.ForeignKey(db_column='fo_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'archivo_importado',
                'ordering': ['-fecha_documento', '-id'],
            },
        ),
    ]
