# Generated by Django 4.2.30 on 2026-10-03 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0002_archivos_importados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha_generacion', '-id']},
        ),
        migrations.AddField(
            model_name='reporte',
            name='archivos',
            field=models.ManyToManyField(blank=True, related_name='informes', to='reportes.archivoimportado'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='contenido',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='parametros',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='tiporeporte',
            name='clave',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fo_usuario',
            field=models.ForeignKey(blank=True, db_column='fo_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
