# Generated by Django 4.2.30 on 2026-09-20 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_tecnicosoporte_supervisor_recursoshumanos_and_more'),
        ('administracion', '0002_documentoinstitucional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.AutoField(db_column='id_capacitacion', primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('modalidad', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'capacitacion',
            },
        ),
        migrations.CreateModel(
            name='CategoriaCurso',
            fields=[
                ('id', models.AutoField(db_column='id_categoria_curso', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categoria_curso',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(db_column='id_curso', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('duracion', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(max_length=255)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('fo_categoria_curso', models.ForeignKey(db_column='fo_categoria_curso', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.categoriacurso')),
            ],
            options={
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='ProgresoCurso',
            fields=[
                ('id', models.AutoField(db_column='id_progreso', primary_key=True, serialize=False)),
                ('porcentaje', models.IntegerField(default=0)),
                ('fo_curso', models.ForeignKey(db_column='fo_curso', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.curso')),
                ('fo_empleado', models.ForeignKey(db_column='fo_empleado', on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado')),
            ],
            options={
                'db_table': 'progreso_curso',
            },
        ),
        migrations.CreateModel(
            name='ParticipanteCapacitacion',
            fields=[
                ('id', models.AutoField(db_column='id_part_cap', primary_key=True, serialize=False)),
                ('asistio', models.BooleanField(default=False)),
                ('fo_capacitacion', models.ForeignKey(db_column='fo_capacitacion', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.capacitacion')),
                ('fo_empleado', models.ForeignKey(db_column='fo_empleado', on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado')),
            ],
            options={
                'db_table': 'participante_capacitacion',
            },
        ),
        migrations.CreateModel(
            name='ModuloCapacitacion',
            fields=[
                ('id', models.AutoField(db_column='id_mod_cap', primary_key=True, serialize=False)),
                ('participantes_activos', models.IntegerField(default=0)),
                ('fo_sistema', models.ForeignKey(db_column='fo_sistema', on_delete=django.db.models.deletion.CASCADE, to='administracion.sistematrainet')),
            ],
            options={
                'db_table': 'modulo_capacitacion',
            },
        ),
        migrations.CreateModel(
            name='MaterialEducativo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='materiales_educativos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fo_curso', models.ForeignKey(db_column='fo_curso', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.curso')),
            ],
            options={
                'db_table': 'material_educativo',
            },
        ),
        migrations.CreateModel(
            name='EvidenciaParticipacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='evidencias_participacion/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fo_participante', models.ForeignKey(db_column='fo_participante', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.participantecapacitacion')),
            ],
            options={
                'db_table': 'evidencia_participacion',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='fo_mod_cap',
            field=models.ForeignKey(db_column='fo_mod_cap', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.modulocapacitacion'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='fo_curso',
            field=models.ForeignKey(db_column='fo_curso', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.curso'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='fo_instructor',
            field=models.ForeignKey(db_column='fo_instructor', on_delete=django.db.models.deletion.CASCADE, to='usuarios.capacitador'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='fo_mod_cap',
            field=models.ForeignKey(db_column='fo_mod_cap', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.modulocapacitacion'),
        ),
    ]
