# Generated by Django 4.2.30 on 2026-09-21 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_tecnicosoporte_supervisor_recursoshumanos_and_more'),
        ('capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursosImpartidos',
            fields=[
                ('id', models.AutoField(db_column='id_cursos_impartidos', primary_key=True, serialize=False)),
                ('fo_capacitador', models.ForeignKey(db_column='fo_capacitador', on_delete=django.db.models.deletion.CASCADE, to='usuarios.capacitador')),
                ('fo_curso', models.ForeignKey(db_column='fo_curso', on_delete=django.db.models.deletion.CASCADE, to='capacitacion.curso')),
            ],
            options={
                'db_table': 'cursos_impartidos',
            },
        ),
    ]
