# Generated by Django 4.2.30 on 2026-09-20 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0002_documentoinstitucional'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaContenido',
            fields=[
                ('id', models.AutoField(db_column='id_cat_cont', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categoria_contenido',
            },
        ),
        migrations.CreateModel(
            name='EstadoContenido',
            fields=[
                ('id', models.AutoField(db_column='id_estado_cont', primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'estado_contenido',
            },
        ),
        migrations.CreateModel(
            name='ModuloInventarioContenido',
            fields=[
                ('id', models.AutoField(db_column='id_mod_inv', primary_key=True, serialize=False)),
                ('fo_sistema', models.ForeignKey(db_column='fo_sistema', on_delete=django.db.models.deletion.CASCADE, to='administracion.sistematrainet')),
            ],
            options={
                'db_table': 'modulo_inventario_contenido',
            },
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(db_column='id_contenido', primary_key=True, serialize=False)),
                ('nombre_contenido', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='inventario_contenido/')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('fo_categoria_cont', models.ForeignKey(db_column='fo_categoria_cont', on_delete=django.db.models.deletion.CASCADE, to='inventario.categoriacontenido')),
                ('fo_estado_cont', models.ForeignKey(db_column='fo_estado_cont', on_delete=django.db.models.deletion.CASCADE, to='inventario.estadocontenido')),
                ('fo_mod_inv', models.ForeignKey(db_column='fo_mod_inv', on_delete=django.db.models.deletion.CASCADE, to='inventario.moduloinventariocontenido')),
            ],
            options={
                'db_table': 'contenido',
            },
        ),
    ]
