# Generated by Django 4.2.30 on 2026-09-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='tipo_contenido',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('presentacion', 'Presentación'), ('manual', 'Manual'), ('otro', 'Otro')], default='otro', max_length=50),
            preserve_default=False,
        ),
    ]
