# Generated by Django 4.2.30 on 2026-09-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=255)),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('fecha_registro', models.DateField(auto_now_add=True, db_column='fecha_registro')),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=255)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False)),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('directivo', 'Directivo'), ('supervisor', 'Supervisor'), ('empleado', 'Empleado'), ('recursos_humanos', 'Recursos Humanos'), ('encargado_formacion', 'Encargado de Formación'), ('encargado_documental', 'Encargado Documental'), ('capacitador', 'Capacitador'), ('tecnico_soporte', 'Técnico de Soporte'), ('encargado_administrativo', 'Encargado Administrativo'), ('proveedor_contenido', 'Proveedor de Contenido')], db_column='rol', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
