# Generated by Django 4.2.30 on 2026-09-20 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnicoSoporte',
            fields=[
                ('id', models.AutoField(db_column='id_tecnico', primary_key=True, serialize=False)),
                ('especialidad_tecnica', models.CharField(max_length=255)),
                ('tickets_resueltos', models.IntegerField(default=0)),
                ('fo_usuario', models.OneToOneField(db_column='fo_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tecnico_soporte',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(db_column='id_supervisor', primary_key=True, serialize=False)),
                ('fo_usuario', models.OneToOneField(db_column='fo_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supervisor',
            },
        ),
        migrations.CreateModel(
            name='RecursosHumanos',
            fields=[
                ('id', models.AutoField(db_column='id_rh', primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=255)),
                ('fo_usuario', models.OneToOneField(db_column='fo_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recursos_humanos',
            },
        ),
        migrations.CreateModel(
            name='ProveedorContenido',
            fields=[
                ('id', models.AutoField(db_column='id_prov_contenido', primary_key=True, serialize=False)),
                ('rating_calidad', models.IntegerField(default=0)),
                ('fo_usuario', models.OneToOneField(db_column='fo_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proveedor_contenido',
            },
        ),
        migrations.CreateModel(
            name='EncargadoFormacion',
            fields=[
                ('id', models.AutoField(db_column='id_enc_formacion', primary_key=True, serialize=False)),
                ('fo_usuario', models.OneToOneField(db_column='fo_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'encargado_formacion',
            },
        ),
        migrations.CreateModel(
            name='EncargadoDocumental',
            fields=[
                ('id', models.AutoField(db_column='id_enc_doc', primary_key=True, serialize=False)),
                ('fo_usuario', models.OneToOneField(db_column='fo_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'encargado_documental',
            },
        ),
        migrations.CreateModel(
            name='EncargadoAdministrativo',
            fields=[
                ('id', models.AutoField(db_column='id_enc_admin', primary_key=True, serialize=False)),
                ('presupuesto_asignado', models.IntegerField(default=0)),
                ('fo_usuario', models.OneToOneField(db_column='fo_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'encargado_administrativo',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(db_column='id_empleado', primary_key=True, serialize=False)),
                ('puesto', models.CharField(max_length=255)),
                ('fecha_ingreso', models.DateField()),
                ('fo_supervisor', models.ForeignKey(db_column='fo_supervisor', on_delete=django.db.models.deletion.CASCADE, to='usuarios.supervisor')),
                ('fo_usuario', models.OneToOneField(db_column='fo_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('id', models.AutoField(db_column='id_directivo', primary_key=True, serialize=False)),
                ('nivel_jerarquia', models.IntegerField(default=1)),
                ('fo_usuario', models.OneToOneField(db_column='fo_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'directivo',
            },
        ),
        migrations.CreateModel(
            name='Capacitador',
            fields=[
                ('id', models.AutoField(db_column='id_capacitador', primary_key=True, serialize=False)),
                ('especialidad_tecnica', models.CharField(max_length=255)),
                ('experiencia', models.IntegerField(default=0)),
                ('fo_usuario', models.OneToOneField(db_column='fo_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'capacitador',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(db_column='id_administrador', primary_key=True, serialize=False)),
                ('fo_usuario', models.OneToOneField(db_column='fo_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'administrador',
            },
        ),
    ]
