# Generated by Django 4.2.30 on 2026-10-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_tecnicosoporte_supervisor_recursoshumanos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(blank=True, db_column='cedula', max_length=10, null=True, unique=True),
        ),
    ]
