# Generated by Django 4.2.30 on 2026-09-21 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0002_documentoinstitucional'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloComprasInternas',
            fields=[
                ('id', models.AutoField(db_column='id_mod_compras', primary_key=True, serialize=False)),
                ('presupuesto_disponible', models.IntegerField(default=0)),
                ('fo_sistema', models.ForeignKey(db_column='fo_sistema', on_delete=django.db.models.deletion.CASCADE, to='administracion.sistematrainet')),
            ],
            options={
                'db_table': 'modulo_compras_internas',
            },
        ),
        migrations.CreateModel(
            name='ProveedorAutorizado',
            fields=[
                ('id', models.AutoField(db_column='id_prov_aut', primary_key=True, serialize=False)),
                ('fo_mod_compras', models.ForeignKey(db_column='fo_mod_compras', on_delete=django.db.models.deletion.CASCADE, to='compras.modulocomprasinternas')),
                ('fo_proveedor', models.ForeignKey(db_column='fo_proveedor', on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
            options={
                'db_table': 'proveedor_autorizado',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(db_column='id_orden', primary_key=True, serialize=False)),
                ('fecha_orden', models.DateField(auto_now_add=True)),
                ('iva', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('compra_confirmada', 'Compra Confirmada'), ('entregada', 'Entregada')], max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('motivo', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('comentario_decision', models.CharField(blank=True, max_length=255)),
                ('factura_comprobante', models.FileField(blank=True, null=True, upload_to='facturas_compras/')),
                ('fo_mod_compras', models.ForeignKey(db_column='fo_mod_compras', on_delete=django.db.models.deletion.CASCADE, to='compras.modulocomprasinternas')),
                ('fo_proveedor', models.ForeignKey(blank=True, db_column='fo_proveedor', null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
                ('fo_usuario', models.ForeignKey(db_column='fo_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orden_compra',
            },
        ),
        migrations.CreateModel(
            name='ItemOrden',
            fields=[
                ('id', models.AutoField(db_column='id_item', primary_key=True, serialize=False)),
                ('descripcion_item', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField(default=0)),
                ('subtotal', models.IntegerField(default=0)),
                ('fo_orden', models.ForeignKey(db_column='fo_orden', on_delete=django.db.models.deletion.CASCADE, to='compras.ordencompra')),
            ],
            options={
                'db_table': 'item_orden',
            },
        ),
        migrations.CreateModel(
            name='CotizacionCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='cotizaciones_compra/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fo_orden', models.ForeignKey(db_column='fo_orden', on_delete=django.db.models.deletion.CASCADE, to='compras.ordencompra')),
            ],
            options={
                'db_table': 'cotizacion_compra',
            },
        ),
    ]
