# Generated by Django 4.2.30 on 2026-10-03 04:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proveedores', '0004_acuerdos_doble_aprobacion'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(db_column='id_articulo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('precio_referencia', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('disponible', models.BooleanField(default=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='articulos/')),
            ],
            options={
                'db_table': 'articulo',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id', models.AutoField(db_column='id_solicitud_compra', primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('area', models.CharField(max_length=255)),
                ('nota', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('comprada', 'Comprada'), ('entregada', 'Entregada')], default='pendiente', max_length=20)),
                ('total_estimado', models.IntegerField(default=0)),
                ('motivo_decision', models.TextField(blank=True, default='')),
                ('fecha_decision', models.DateTimeField(blank=True, null=True)),
                ('fo_aprobador', models.ForeignKey(blank=True, db_column='fo_aprobador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_compra_decididas', to=settings.AUTH_USER_MODEL)),
                ('fo_mod_compras', models.ForeignKey(db_column='fo_mod_compras', on_delete=django.db.models.deletion.CASCADE, to='compras.modulocomprasinternas')),
                ('fo_solicitante', models.ForeignKey(db_column='fo_solicitante', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_compra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitud_compra',
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitud',
            fields=[
                ('id', models.AutoField(db_column='id_item_solicitud', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.IntegerField(default=0)),
                ('justificacion', models.TextField(blank=True, default='')),
                ('fo_articulo', models.ForeignKey(db_column='fo_articulo', on_delete=django.db.models.deletion.PROTECT, to='compras.articulo')),
                ('fo_solicitud', models.ForeignKey(db_column='fo_solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.solicitudcompra')),
            ],
            options={
                'db_table': 'item_solicitud',
            },
        ),
        migrations.CreateModel(
            name='CategoriaArticulo',
            fields=[
                ('id', models.AutoField(db_column='id_categoria_articulo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('icono', models.CharField(default='bi-box-seam', max_length=50)),
                ('proveedores', models.ManyToManyField(blank=True, related_name='categorias_articulo', to='proveedores.proveedor')),
            ],
            options={
                'db_table': 'categoria_articulo',
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='fo_categoria',
            field=models.ForeignKey(db_column='fo_categoria', on_delete=django.db.models.deletion.PROTECT, to='compras.categoriaarticulo'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='fo_mod_compras',
            field=models.ForeignKey(db_column='fo_mod_compras', on_delete=django.db.models.deletion.CASCADE, to='compras.modulocomprasinternas'),
        ),
    ]
