# Generated by Django 4.2.30 on 2026-10-03 05:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proveedores', '0004_acuerdos_doble_aprobacion'),
        ('compras', '0002_catalogo_y_solicitud_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacioncompra',
            name='fo_proveedor',
            field=models.ForeignKey(blank=True, db_column='fo_proveedor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_compra', to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='cotizacioncompra',
            name='fo_solicitud',
            field=models.ForeignKey(blank=True, db_column='fo_solicitud', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='compras.solicitudcompra'),
        ),
        migrations.AddField(
            model_name='cotizacioncompra',
            name='fo_usuario',
            field=models.ForeignKey(blank=True, db_column='fo_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_compra_cargadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacioncompra',
            name='iva',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cotizacioncompra',
            name='monto_total',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='fecha_compra',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='fecha_reclamo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='fo_comprador',
            field=models.ForeignKey(blank=True, db_column='fo_comprador', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_compra_confirmadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='fo_cotizacion_elegida',
            field=models.ForeignKey(blank=True, db_column='fo_cotizacion_elegida', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='compras.cotizacioncompra'),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='fo_entregado_por',
            field=models.ForeignKey(blank=True, db_column='fo_entregado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_compra_entregadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='fo_orden',
            field=models.ForeignKey(blank=True, db_column='fo_orden', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='compras.ordencompra'),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='motivo_reclamo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='cotizacioncompra',
            name='fo_orden',
            field=models.ForeignKey(blank=True, db_column='fo_orden', null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.ordencompra'),
        ),
        migrations.AlterField(
            model_name='solicitudcompra',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('comprada', 'Comprada'), ('entregada', 'Entregada'), ('en_revision', 'En revisión'), ('recibida', 'Recibida')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.AutoField(db_column='id_factura_compra', primary_key=True, serialize=False)),
                ('archivo', models.FileField(upload_to='facturas_compra/')),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fo_solicitud', models.ForeignKey(db_column='fo_solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='compras.solicitudcompra')),
                ('fo_usuario', models.ForeignKey(blank=True, db_column='fo_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_compra_cargadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'factura_compra',
            },
        ),
        migrations.CreateModel(
            name='EventoSolicitud',
            fields=[
                ('id', models.AutoField(db_column='id_evento_solicitud', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('creada', 'Creada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('comprada', 'Comprada'), ('entregada', 'Entregada'), ('recibida', 'Recibida'), ('no_recibida', 'Reportada como no recibida'), ('reentregada', 'Reentregada')], max_length=20)),
                ('detalle', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fo_solicitud', models.ForeignKey(db_column='fo_solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='compras.solicitudcompra')),
                ('fo_usuario', models.ForeignKey(blank=True, db_column='fo_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_solicitud_compra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evento_solicitud',
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
