# Generated by Django 4.2.30 on 2026-10-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_cotizaciones_compra_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosolicitud',
            name='tipo',
            field=models.CharField(choices=[('creada', 'Creada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('comprada', 'Comprada'), ('entregada', 'Entregada'), ('recibida', 'Recibida'), ('no_recibida', 'Reportada como no recibida'), ('reentregada', 'Reentregada'), ('observacion', 'Observación')], max_length=20),
        ),
    ]
