# Generated by Django 4.2.30 on 2026-09-20 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0002_documentoinstitucional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.AutoField(db_column='id_cat_doc', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categoria_documento',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(db_column='id_documento', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('version', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('tamanio', models.IntegerField(default=0)),
                ('fo_categoria_documento', models.ForeignKey(db_column='fo_categoria_documento', on_delete=django.db.models.deletion.CASCADE, to='documentos.categoriadocumento')),
            ],
            options={
                'db_table': 'documento',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(db_column='id_tipo_documento', primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='ModuloGestionDocumental',
            fields=[
                ('id', models.AutoField(db_column='id_mod_doc', primary_key=True, serialize=False)),
                ('documentos_almacenados', models.IntegerField(default=0)),
                ('fo_sistema', models.ForeignKey(db_column='fo_sistema', on_delete=django.db.models.deletion.CASCADE, to='administracion.sistematrainet')),
            ],
            options={
                'db_table': 'modulo_gestion_documental',
            },
        ),
        migrations.CreateModel(
            name='HistorialAccesoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('consulta', 'Consulta'), ('descarga', 'Descarga')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fo_documento', models.ForeignKey(db_column='fo_documento', on_delete=django.db.models.deletion.CASCADE, to='documentos.documento')),
                ('fo_usuario', models.ForeignKey(db_column='fo_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_acceso_documento',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='fo_mod_doc',
            field=models.ForeignKey(db_column='fo_mod_doc', on_delete=django.db.models.deletion.CASCADE, to='documentos.modulogestiondocumental'),
        ),
        migrations.AddField(
            model_name='documento',
            name='fo_tipo_documento',
            field=models.ForeignKey(db_column='fo_tipo_documento', on_delete=django.db.models.deletion.CASCADE, to='documentos.tipodocumento'),
        ),
        migrations.AddField(
            model_name='categoriadocumento',
            name='fo_mod_doc',
            field=models.ForeignKey(db_column='fo_mod_doc', on_delete=django.db.models.deletion.CASCADE, to='documentos.modulogestiondocumental'),
        ),
    ]
