# Generated by Django 4.2.30 on 2026-09-21 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_tecnicosoporte_supervisor_recursoshumanos_and_more'),
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoAcceso',
            fields=[
                ('id', models.AutoField(db_column='id_tipo_doc', primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=255)),
                ('fo_enc_doc', models.ForeignKey(db_column='fo_enc_doc', on_delete=django.db.models.deletion.CASCADE, to='usuarios.encargadodocumental')),
            ],
            options={
                'db_table': 'tipo_documento_acceso',
            },
        ),
        migrations.CreateModel(
            name='CategoriaAccesoDoc',
            fields=[
                ('id', models.AutoField(db_column='id_cat_acceso', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=255)),
                ('fo_enc_doc', models.ForeignKey(db_column='fo_enc_doc', on_delete=django.db.models.deletion.CASCADE, to='usuarios.encargadodocumental')),
            ],
            options={
                'db_table': 'categoria_acceso_doc',
            },
        ),
    ]
